In [1]:
import pandas as pd
import os
import requests
import quandl
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from dotenv import load_dotenv
from collections import Counter
import pandas_profiling

In [2]:
DataFrame='tableau_project.csv'

def read(DataFrame):
    data = pd.read_csv(DataFrame)
    return data

In [3]:
data = read(DataFrame)
data

,Unnamed: 0,journey_id,vehicle_type_id,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,...,price_distance,price_duration,distance,duration,source,rider_waiting_time,driver_waiting_time,price_supplements,discount,rating
0,0,93e6d216088af74c32183283d4bb2953,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 11:08:59,19.431363,-99.195362,2017-12-16 11:37:32,19.406438,-99.175260,...,"5,204",0,"7,943","1,058",Android,590,48,662,0,9.0
1,1,444b084ec64244919afadfba879876a3,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 11:06:16,19.431567,-99.195368,2017-12-16 11:07:21,NaN,NaN,...,0,0,0,0,iPhone,NaN,NaN,0,0,9.0
2,2,dbcc57f4e7606a71c74c6e4666a977a4,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 22:58:37,19.422052,-99.174499,2017-11-24 23:27:05,19.438666,-99.180821,...,"3,552",0,"3,054",689,Android,923,4,0,0,10.0
3,3,1ffe9a24033847148c683574985df56c,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 09:17:08,19.433119,-99.154844,2017-12-16 09:17:30,19.290148,-99.144407,...,0,0,0,0,iPhone,NaN,NaN,0,0,9.0
4,4,fb1ef7d070724482a33be41f27737ea5,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 18:11:00,19.440996,-99.183581,2017-11-24 18:31:31,19.422815,-99.174865,...,"2,974",12,"2,859",887,iPhone,329,36,0,0,8.0
5,5,310f2f7103dd41c9811bffa771776648,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 15:34:53,19.421856,-99.174361,2017-11-24 15:53:30,19.440311,-99.184146,...,"3,346",290,"3,176","1,028",iPhone,73,369,0,0,8.0
6,6,0a5bb1448fa2418581b7171df9f6d1a4,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 15:10:23,19.419962,-99.171955,2017-11-24 15:10:42,19.441434,-99.183503,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,10.0
7,7,643a2da9e5f9457ab4a1706875c92d10,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 15:09:29,19.419962,-99.171955,2017-11-24 15:47:42,19.441434,-99.183503,...,"4,367","2,082","3,008","1,505",iPhone,770,799,0,0,10.0
8,8,38aa6d5e20294992a6c31827d3a5a5c7,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 14:31:58,19.406538,-99.169710,2017-11-24 14:32:56,19.421960,-99.174559,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,10.0
9,9,bd801b036699c6fdfdc530a6334ae88f,077866c3fd1a75f51ca7f8eae166ae32,reserved,2017-11-24 14:20:00,19.438666,-99.180821,2017-11-24 14:36:44,19.423103,-99.174878,...,"4,063",0,"3,034",958,Android,"1,655","1,039",0,0,10.0
10,10,d61f40bbe1f942a8b9acab3a3f3d74f3,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 23:03:44,19.421545,-99.174222,2017-11-30 23:03:50,19.442719,-99.201140,...,0,0,0,0,iPhone,NaN,NaN,0,0,10.0
11,11,3fbde2354fd74135a87ce20b14af9a25,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 23:02:14,19.421541,-99.174171,2017-11-30 23:35:45,19.442719,-99.201140,...,"6,924",0,"5,083","1,253",iPhone,729,6,0,0,10.0
12,12,616bacc8c3d59829127c22f8eeb2ad34,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 03:37:44,19.422815,-99.174865,2017-11-30 04:02:56,19.406438,-99.175260,...,"3,766",0,"2,766",841,Android,633,97,0,0,9.0
13,13,0cdf9c4e11e5ed944879473e036ddc02,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 03:02:10,19.415241,-99.178212,2017-11-30 03:02:23,19.407004,-99.175830,...,0,0,0,0,Android,NaN,NaN,0,0,9.0
14,14,e0cd89ab902bcc6e6ba14de7606ee2d8,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 03:01:26,19.422034,-99.174665,2017-11-30 03:01:57,19.438666,-99.180821,...,0,0,0,0,Android,NaN,NaN,0,0,9.0
15,15,6dc46eede5d54730bdb0a9919ec0a2f1,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 01:04:57,19.441434,-99.183503,2017-11-30 02:14:25,19.439331,-99.202260,...,"9,279",125,"8,254","3,566",iPhone,589,158,0,0,10.0
16,16,65fa0803b8da46e8afc7a88909b3eaca,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 02:42:52,19.406538,-99.169710,2017-12-16 02:43:04,19.425151,-99.178225,...,0,0,0,0,iPhone,NaN,NaN,0,0,9.0
17,17,6694715bbad44cd1acf8a0eb665bef6f,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-12-16 02:25:34,19.406353,-99.175294,2017-12-16 02:51:58,19.432267,-99.154651,...,"5,299",0,"5,600","1,073",iPhone,477,11,0,0,8.0
18,18,6f21e8cc076c1a94e0cf88f2cb6fd12e,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 04:26:15,19.422815,-99.174865,2017-11-24 04:52:20,19.406438,-99.175260,...,"2,912",0,"3,187",930,Android,576,180,0,0,9.0
19,19,ccd0e6655ca5acec2b2b3f4776b26977,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 04:24:26,19.422815,-99.174865,2017-11-24 04:26:09,19.406438,-99.175260,...,NaN,NaN,0,0,Android,NaN,NaN,0,0,9.0
20,20,496d65d80daf420ea0eac86300c804d5,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 04:13:41,19.421865,-99.174460,2017-11-24 04:15:25,19.440528,-99.176656,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,6.0
21,21,b10f791840c54bd79c1cbd9d7f7e7cf8,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 19:03:40,19.440754,-99.183578,2017-11-30 19:39:23,19.422815,-99.174865,...,"3,179",0,"3,073","1,259",iPhone,873,10,0,0,8.0
22,22,16e583043e194fa594856254cc5709e3,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 19:01:29,19.441409,-99.184146,2017-11-30 19:29:52,19.427445,-99.170818,...,"3,108",0,"2,923","1,485",iPhone,205,262,0,0,10.0
23,23,e080e1fd0f754ea5815ac1ee3105aebc,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 16:40:40,19.421830,-99.174441,2017-11-30 17:08:04,19.440311,-99.184146,...,"3,643",0,"2,516",783,iPhone,856,7,0,0,8.0
24,24,1c0a29b9c043b6da738908d0d81ab74b,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 02:12:27,19.438666,-99.180821,2017-11-24 02:57:54,19.406134,-99.176266,...,"6,582",0,"4,849","1,682",Android,"1,011",194,0,0,10.0
25,25,78b1537c5945b652a8cc41b6814dc701,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 02:08:47,19.438666,-99.180821,2017-11-24 02:12:16,19.406134,-99.176266,...,NaN,NaN,0,0,Android,NaN,NaN,0,0,10.0
26,26,d075f6d50d0044eaaf5288afb3208b61,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 16:17:50,19.441256,-99.183574,2017-11-30 16:34:40,19.422815,-99.174865,...,"3,644",0,"2,714",838,iPhone,163,6,0,0,6.0
27,27,4c565fb5efc94f92b3797868629b4280,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 15:14:57,19.419962,-99.171955,2017-11-30 16:03:54,19.441434,-99.183503,...,"4,092","1,346","3,895","2,270",iPhone,648,622,0,0,10.0
28,28,b17141a7c14449e0b4aa8f989cb2808a,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-30 15:06:39,19.419962,-99.171955,2017-11-30 15:06:56,19.441434,-99.183503,...,0,0,0,0,iPhone,NaN,NaN,0,0,10.0
29,29,f22fde5acdab4bfe9d9a6804b9c31aa6,077866c3fd1a75f51ca7f8eae166ae32,asap,2017-11-24 00:39:36,19.441358,-99.182789,2017-11-24 00:39:54,19.419962,-99.171955,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3834,3834,c995af5b6b0c4ff8b3ad3576f7bd99ac,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-07 19:54:21,19.364772,-99.267162,2017-04-07 19:55:23,19.498778,-99.231474,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,8.0
3835,3835,e69689033176d8272bcd74b3ebc49ddd,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-07 17:31:49,19.441380,-99.183926,2017-04-07 17:57:33,19.423103,-99.174878,...,"3,778",0,"3,769","1,265",Android,263,4,0,0,9.0
3836,3836,b0ddd60ef006424cb9ffecc8d2e748de,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-07 20:36:05,19.376909,-99.254901,2017-04-07 20:37:26,19.379486,-99.253980,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,9.0
3837,3837,176d752989bd438a86b77e18cedda299,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-07 20:39:48,19.376909,-99.254901,2017-04-07 20:42:08,19.379486,-99.253980,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,9.0
3838,3838,62194c52f9474cda977ea3af14746c3d,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-08 00:24:25,19.419364,-99.169973,2017-04-08 00:27:47,19.433624,-99.182673,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,8.0
3839,3839,c01ecf45e09a425dbcc4a4cdfd4a2b07,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-07 22:54:28,19.423159,-99.174806,2017-04-07 23:37:27,19.356000,-99.275269,...,"17,800",0,"15,001","2,020",iPhone,498,5,0,0,9.0
3840,3840,3135fb241adf47139f0707b9c86ca21b,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-08 00:45:40,19.498972,-99.231669,2017-04-08 01:36:04,19.423091,-99.170269,...,"16,026",0,"14,854","2,456",iPhone,524,101,"1,477",0,8.0
3841,3841,9bcf5fea62f74130a843992a495017bc,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-08 00:19:06,19.379486,-99.253980,2017-04-08 01:48:47,19.402877,-99.098333,...,"24,138",649,"29,868","4,626",iPhone,676,455,"4,600",0,9.0
3842,3842,658bb64983ba4f9999087cc62992baf5,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-08 06:23:34,19.419770,-99.165930,2017-04-08 06:53:54,19.379486,-99.253980,...,"10,852",0,"14,602","1,654",iPhone,142,169,0,0,9.0
3843,3843,f604766ae98f44f4b71353cff48a573d,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-08 18:40:23,19.379486,-99.253980,2017-04-08 18:40:44,19.376909,-99.254901,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,9.0
3844,3844,3a44e92e9ab3c0168bfc432d83b6a6fc,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-08 16:58:27,19.423091,-99.170269,2017-04-08 17:29:20,19.432232,-99.147815,...,"3,128",0,"2,593","1,487",Android,326,20,0,0,9.0
3845,3845,8f122802d3304edcbd8f3433c3be1977,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 05:01:36,19.364605,-99.259426,2017-04-10 05:04:47,19.379486,-99.253980,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,9.0
3846,3846,5b0026f242eb46eeb9972618302841db,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 12:39:46,19.379486,-99.253980,2017-04-10 12:42:33,19.376909,-99.254901,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,9.0
3847,3847,9c8f4fd9b47f42899abcd8084404d1c6,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 12:50:50,19.356000,-99.275269,2017-04-10 13:35:44,19.441503,-99.183563,...,"18,610",0,"17,033","2,145",iPhone,503,82,0,0,9.0
3848,3848,ec8127d5d89a434ead2baf72781b36fa,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 12:42:39,19.379486,-99.253980,2017-04-10 13:07:27,19.376909,-99.254901,...,"2,246","1,487","1,809","1,023",iPhone,456,656,0,0,9.0
3849,3849,778615f20bf295fa01a8df8ebd6b1ad3,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 13:17:10,19.423091,-99.170269,2017-04-10 13:37:01,19.441380,-99.183926,...,"4,421",0,"3,025","1,041",Android,132,54,0,0,9.0
3850,3850,f6ac648dbde142ab81e96140a0ada4a3,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 18:52:51,19.376909,-99.254901,2017-04-10 19:08:08,19.379486,-99.253980,...,"2,071",24,"1,583",662,iPhone,243,305,0,0,9.0
3851,3851,4899235c786547e8bd7f9965999c55e3,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-10 20:50:10,19.379486,-99.253980,2017-04-10 21:15:01,19.376909,-99.254901,...,"2,045","2,236","1,622","1,167",iPhone,311,836,0,0,9.0
3852,3852,8b460119b4fb09e10069f84a3e450562,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-11 00:12:11,19.441380,-99.183926,2017-04-11 00:43:13,19.423091,-99.170269,...,"7,188",356,"4,260","1,556",Android,285,1,0,0,9.0
3853,3853,ee4075c3d2ea4a29b5c04e7a56db8ec7,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-11 13:12:54,19.356000,-99.275269,2017-04-11 13:50:54,19.422749,-99.174937,...,"16,643","1,038","15,204","2,171",iPhone,69,549,0,0,9.0
3854,3854,ac3e367ee2014c799f334de79664bfbb,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-11 14:38:15,19.423044,-99.174936,2017-04-11 15:03:51,19.441503,-99.183563,...,"4,512",0,"3,541","1,049",iPhone,473,51,0,0,9.0
3855,3855,bca3ab7e8a434fbeba4a62654f69569e,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-11 18:04:01,19.438306,-99.202551,2017-04-11 18:06:55,19.379486,-99.253980,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,9.0
3856,3856,8f8a57e89d4d4865ba3e971de695795e,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-23 16:43:22,19.425045,-99.170860,2017-04-23 17:14:27,19.355050,-99.162281,...,"11,052",0,"14,041","1,448",iPhone,394,69,0,0,6.0
3857,3857,5e52df2ed30f4e20b853ff53c0793270,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-05-02 15:40:18,19.425047,-99.170855,2017-05-02 17:20:42,19.260422,-99.100854,...,"27,294",179,"40,514","5,439",iPhone,499,46,"2,419",0,7.0
3858,3858,647bcbb8b63e4a2ea5ab3df6b58f0752,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-23 16:44:57,19.425045,-99.170860,2017-04-23 17:22:23,19.355143,-99.162525,...,"11,031",0,"14,056","1,691",iPhone,495,45,0,0,6.0
3859,3859,d850a4a8d7a244b990575a4339ee0842,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-17 02:26:44,19.435400,-99.148699,2017-04-17 02:52:03,19.425045,-99.170860,...,"4,134",0,"3,204",857,iPhone,650,125,0,0,6.0
3860,3860,1688ee212d2d43bbbe5efa46b70901ab,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-16 23:58:41,19.425045,-99.170860,2017-04-17 00:23:32,19.432602,-99.133205,...,"5,752",0,"4,417","1,137",iPhone,330,6,0,0,6.0
3861,3861,349a85cc381e4e0b8401c1f2bde441de,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-17 02:00:27,19.435400,-99.148699,2017-04-17 02:12:07,NaN,NaN,...,0,0,0,0,iPhone,669,NaN,0,0,6.0
3862,3862,f7e6890738a345578e7cb3543af774e1,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-16 23:41:20,19.425390,-99.207499,2017-04-16 23:53:33,19.432602,-99.133205,...,0,0,5,252,iPhone,423,NaN,0,0,6.0
3863,3863,67d1a13aa7b24024892ffca4585a68e2,21620ea5749f2e0679a8c72c7fbafb9e,asap,2017-04-17 02:13:29,19.435400,-99.148699,2017-04-17 02:24:35,NaN,NaN,...,NaN,NaN,0,0,iPhone,NaN,NaN,0,0,6.0

In [4]:
data = data.fillna('unknown')
data = data.set_index('Unnamed: 0')

In [5]:
data.columns
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3864 entries, 0 to 3863
Data columns (total 21 columns):
journey_id             3864 non-null object
vehicle_type_id        3864 non-null object
start_type             3864 non-null object
start_at               3864 non-null object
start_lat              3864 non-null float64
start_lon              3864 non-null float64
end_at                 3864 non-null object
end_lat                3864 non-null object
end_lon                3864 non-null object
end_state              3864 non-null object
price                  3864 non-null object
price_distance         3864 non-null object
price_duration         3864 non-null object
distance               3864 non-null object
duration               3864 non-null object
source                 3864 non-null object
rider_waiting_time     3864 non-null object
driver_waiting_time    3864 non-null object
price_supplements      3864 non-null object
discount               3864 non-null object
rating                 3864 non-null float64
dtypes: float64(3), object(18)
memory usage: 664.1+ KB

In [6]:
data['vehicle_type_id'] = data['vehicle_type_id'].replace({'21620ea5749f2e0679a8c72c7fbafb9e': 'Vehicle 1', 
                                                           '077866c3fd1a75f51ca7f8eae166ae32': 'Vehicle 2'})

data['start_lat'] = data['start_lat'].astype(str)
data['start_lon'] = data['start_lon'].astype(str)
data['end_lat'] = data['end_lat'].astype(str)
data['end_lon'] = data['end_lon'].astype(str)

In [7]:
data['end_state'].value_counts()
#quitar discount

drop off         2685
rider cancel     1146
not found          20
no show            12
driver cancel       1
Name: end_state, dtype: int64

In [8]:
data = data.drop(data[data['end_state']=='not fount'].index)
data = data.drop(data[data['end_state']=='no show'].index)
data = data.drop(data[data['end_state']=='driver cancel'].index)

In [9]:
data.head()

,journey_id,vehicle_type_id,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,...,price_distance,price_duration,distance,duration,source,rider_waiting_time,driver_waiting_time,price_supplements,discount,rating
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,93e6d216088af74c32183283d4bb2953,Vehicle 2,asap,2017-12-16 11:08:59,19.4313629,-99.195362,2017-12-16 11:37:32,19.4064378,-99.1752599,drop off,...,"5,204",0,"7,943","1,058",Android,590,48,662,0,9.0
1,444b084ec64244919afadfba879876a3,Vehicle 2,asap,2017-12-16 11:06:16,19.431566759000003,-99.19536788030001,2017-12-16 11:07:21,unknown,unknown,rider cancel,...,0,0,0,0,iPhone,unknown,unknown,0,0,9.0
2,dbcc57f4e7606a71c74c6e4666a977a4,Vehicle 2,asap,2017-11-24 22:58:37,19.4220518545,-99.17449861760001,2017-11-24 23:27:05,19.438666,-99.1808212,drop off,...,"3,552",0,"3,054",689,Android,923,4,0,0,10.0
3,1ffe9a24033847148c683574985df56c,Vehicle 2,asap,2017-12-16 09:17:08,19.4331187103,-99.15484447969999,2017-12-16 09:17:30,19.2901477,-99.1444066,rider cancel,...,0,0,0,0,iPhone,unknown,unknown,0,0,9.0
4,fb1ef7d070724482a33be41f27737ea5,Vehicle 2,asap,2017-11-24 18:11:00,19.440996018499998,-99.18358124790001,2017-11-24 18:31:31,19.4228147,-99.1748655,drop off,...,"2,974",12,"2,859",887,iPhone,329,36,0,0,8.0

In [10]:
data.columns

Index(['journey_id', 'vehicle_type_id', 'start_type', 'start_at', 'start_lat',
       'start_lon', 'end_at', 'end_lat', 'end_lon', 'end_state', 'price',
       'price_distance', 'price_duration', 'distance', 'duration', 'source',
       'rider_waiting_time', 'driver_waiting_time', 'price_supplements',
       'discount', 'rating'],
      dtype='object')

In [11]:
colnames = ['journey_id', 'start_type', 'start_at', 'start_lat',
                'start_lon', 'end_at', 'end_lat', 'end_lon', 'end_state', 'price',
                'price_distance', 'price_duration', 'distance', 'duration', 'source',
                'rider_waiting_time', 'driver_waiting_time', 'price_supplements', 
                'rating']
data = pd.DataFrame(data, columns=colnames)

In [12]:
pandas_profiling.ProfileReport(data)

In [13]:
data.to_csv('data_cleaned.csv')

In [14]:
data.head()

,journey_id,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,price,price_distance,price_duration,distance,duration,source,rider_waiting_time,driver_waiting_time,price_supplements,rating
Unnamed: 0,,,,,,,,,,,,,,,,,,,
0,93e6d216088af74c32183283d4bb2953,asap,2017-12-16 11:08:59,19.4313629,-99.195362,2017-12-16 11:37:32,19.4064378,-99.1752599,drop off,"5,866","5,204",0,"7,943","1,058",Android,590,48,662,9.0
1,444b084ec64244919afadfba879876a3,asap,2017-12-16 11:06:16,19.431566759000003,-99.19536788030001,2017-12-16 11:07:21,unknown,unknown,rider cancel,0,0,0,0,0,iPhone,unknown,unknown,0,9.0
2,dbcc57f4e7606a71c74c6e4666a977a4,asap,2017-11-24 22:58:37,19.4220518545,-99.17449861760001,2017-11-24 23:27:05,19.438666,-99.1808212,drop off,"4,000","3,552",0,"3,054",689,Android,923,4,0,10.0
3,1ffe9a24033847148c683574985df56c,asap,2017-12-16 09:17:08,19.4331187103,-99.15484447969999,2017-12-16 09:17:30,19.2901477,-99.1444066,rider cancel,0,0,0,0,0,iPhone,unknown,unknown,0,9.0
4,fb1ef7d070724482a33be41f27737ea5,asap,2017-11-24 18:11:00,19.440996018499998,-99.18358124790001,2017-11-24 18:31:31,19.4228147,-99.1748655,drop off,"4,000","2,974",12,"2,859",887,iPhone,329,36,0,8.0